sudo: required

language: python

services:
  - docker

before_install:
- docker login -e="$DOCKER_HUB_EMAIL" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"

install:
- docker build --no-cache -t celestialstats/clientdiscord:latest .

#script:
#- docker run -t -i celestialstats/clientdiscord:latest python -m unittest discover -v /cs/clientdiscord/

after_success:
- docker push celestialstats/clientdiscord:latest
